name: Frontend React App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  AZURE_STATIC_WEB_APP_NAME: ${{ vars.AZURE_STATIC_WEB_APP_NAME || 'stapp-afiliados-frontend' }}

jobs:
  build-and-deploy:
    name: Build and Deploy React App
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend
      
    - name: Run tests
      run: npm test -- --passWithNoTests
      working-directory: ./frontend
      
    - name: Build
      run: npm run build
      working-directory: ./frontend
      env:
        CI: false
        REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: ./frontend/build
        
    # Deploy to Azure Static Web Apps (two options provided)
    
    # Option 1: Using Azure Static Web Apps action (recommended for Static Web Apps)
    - name: Deploy to Azure Static Web App
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "frontend"
        output_location: "build"
        skip_app_build: true
      
    # Option 2: Alternative deployment method for Storage Account static websites
    # Uncomment if using Azure Storage instead of Static Web Apps
    #- name: Deploy to Azure Storage Account
    #  if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    #  uses: azure/CLI@v1
    #  with:
    #    inlineScript: |
    #      az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --auth-mode key --account-key ${{ secrets.AZURE_STORAGE_KEY }} --destination '$web' --source ./frontend/build
